### ISSUE TITLE
rake multiverse failing on clean repo :/

### ISSUE THREAD

**Issue by tkrajcar** [reedsport-computer-repair/straw#1]
Anxious to make hay while the sun shines -  running `rake multiverse` I get the following error:

```
/.../gems/bundler-1.7.12/lib/bundler/resolver.rb:368:in `resolve':
Could not find gem 'bales (~> 2.0.0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
    from /.../gems/bundler-1.7.12/lib/bundler/resolver.rb:166:in `start'
    from /.../gems/bundler-1.7.12/lib/bundler/resolver.rb:129:in `resolve'
    from /.../gems/bundler-1.7.12/lib/bundler/definition.rb:193:in `resolve'
    from /.../gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
    from test/runner.rb:25:in `run'
    from test/runner.rb:62:in `<main>'
```

I can install the gem, but it seems like the tests should run from a clean install, shouldn't they? :expressionless:

**Comment by thejonanshow** [comment]
:+1:
